# Generated by Django 5.2.5 on 2025-08-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_academicprogram_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcareer',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programrequirement',
            name='program',
        ),
        migrations.DeleteModel(
            name='ProgramSpecialization',
        ),
        migrations.DeleteModel(
            name='ProgramCareer',
        ),
        migrations.DeleteModel(
            name='AcademicProgram',
        ),
        migrations.DeleteModel(
            name='ProgramRequirement',
        ),
    ]
