# Generated by Django 4.2.4 on 2025-09-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0003_remove_programcareer_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full program title (e.g., Bachelor of Science in Information Technology)', max_length=200)),
                ('short_title', models.CharField(help_text='Short version of the title', max_length=100)),
                ('program_type', models.CharField(choices=[('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('MA', 'Master of Arts'), ('MS', 'Master of Science')], default='BS', max_length=2)),
                ('description', models.TextField(help_text='Brief description of the program')),
                ('duration_years', models.PositiveIntegerField(default=4, help_text='Duration in years')),
                ('total_units', models.PositiveIntegerField(default=120, help_text='Total number of units')),
                ('program_overview', models.TextField(help_text='Detailed program overview')),
                ('core_courses', models.JSONField(default=list, help_text='List of core courses')),
                ('career_prospects', models.TextField(help_text='Career opportunities for graduates')),
                ('general_requirements', models.JSONField(default=list, help_text='General admission requirements')),
                ('specific_requirements', models.JSONField(default=list, help_text='Program-specific requirements')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this program is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display on website')),
            ],
            options={
                'verbose_name': 'Academic Program',
                'verbose_name_plural': 'Academic Programs',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Specialization name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the specialization')),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='portal.academicprogram')),
            ],
            options={
                'verbose_name': 'Program Specialization',
                'verbose_name_plural': 'Program Specializations',
                'ordering': ['name'],
            },
        ),
    ]
