# Generated by Django 4.2.4 on 2025-09-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogram',
            name='core_courses',
            field=models.TextField(default='', help_text='List of core courses (one per line)'),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='general_requirements',
            field=models.TextField(default='', help_text='General admission requirements (one per line)'),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='specific_requirements',
            field=models.TextField(default='', help_text='Program-specific requirements (one per line)'),
        ),
    ]
