# Generated by Django 4.2.4 on 2025-09-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_academicprogram_core_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprogram',
            name='career_prospects',
        ),
        migrations.RemoveField(
            model_name='academicprogram',
            name='core_courses',
        ),
        migrations.RemoveField(
            model_name='academicprogram',
            name='general_requirements',
        ),
        migrations.RemoveField(
            model_name='academicprogram',
            name='program_overview',
        ),
        migrations.RemoveField(
            model_name='academicprogram',
            name='specific_requirements',
        ),
    ]
