# Generated by Django 5.2.5 on 2025-09-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='details',
            field=models.TextField(blank=True, help_text='Full details shown in modal; falls back to body if empty'),
        ),
    ]
