# Generated by Django 5.2.5 on 2025-08-27 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicprogram',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='programspecialization',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='academicprogram',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='academicprogram',
            old_name='units_required',
            new_name='total_units',
        ),
        migrations.RemoveField(
            model_name='academicprogram',
            name='duration',
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='degree_level',
            field=models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate'), ('POSTGRADUATE', 'Postgraduate')], default='UNDERGRADUATE', max_length=20),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='duration_years',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='tuition_fee_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='programspecialization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='degree_type',
            field=models.CharField(choices=[('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('AA', 'Associate in Arts'), ('AS', 'Associate in Science')], default='BS', max_length=2),
        ),
        migrations.AlterField(
            model_name='programspecialization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProgramCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='portal.academicprogram')),
            ],
            options={
                'ordering': ['career_title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('units_required', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='portal.academicprogram')),
            ],
            options={
                'ordering': ['requirement_type', 'description'],
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
