# Generated by Django 4.2.4 on 2025-09-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_academicprogram_career_prospects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='with_enhancements',
            field=models.PositiveIntegerField(default=0, help_text='Number of enhancements'),
        ),
    ]
