# Generated by Django 4.2.4 on 2025-09-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_academicprogram_with_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='career_prospects',
            field=models.TextField(blank=True, help_text='Career prospects and opportunities'),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='core_courses',
            field=models.TextField(blank=True, help_text='Core courses (one per line)'),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='program_overview',
            field=models.TextField(blank=True, help_text='Detailed program overview and objectives'),
        ),
    ]
