# Generated by Django 5.2.5 on 2025-09-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_academicprogram_career_prospects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Label shown to users, e.g., Application Period', max_length=120)),
                ('start_date', models.DateField(help_text='Start date of the period or event')),
                ('end_date', models.DateField(help_text='End date of the period or event')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admissions Important Date',
                'verbose_name_plural': 'Admissions Important Dates',
                'ordering': ['display_order', 'start_date', 'title'],
            },
        ),
    ]
