# Generated by Django 4.2.4 on 2025-09-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_announcement_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the event')),
                ('details', models.TextField(blank=True, help_text='Full details shown in modal; falls back to description if empty')),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('start_time', models.TimeField(help_text='Start time of the event')),
                ('end_time', models.TimeField(help_text='End time of the event')),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['display_order', 'event_date', 'start_time', 'title'],
            },
        ),
    ]
