# Generated by Django 4.2.4 on 2025-09-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Achievement title', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the achievement')),
                ('details', models.TextField(blank=True, help_text='Full details shown in modal; falls back to description if empty')),
                ('achievement_date', models.DateField(help_text='Date of the achievement')),
                ('category', models.CharField(default='Achievement', help_text='Category (e.g., Achievement, Press Release, Award)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['display_order', '-achievement_date', 'title'],
            },
        ),
    ]
